### PR TITLE
Site tweaks

### PR DESCRIPTION
**Pull request by jessepinho**
Wanted to open a PR to keep track of remaining tweaks/changes/questions

### CODE REVIEW

**Comment by jessepinho** [comment]
~~`{{ root_url }}` is empty.~~

**Comment by jessepinho** [comment]
Here's what I changed the header to (instead of pasting together images). Let me know what you think.

image

**Comment by jessepinho** [comment]
~~The modified header height causes problems when making browser more narrow (and thus making header shorter, due to its aspect ratio).~~

**Comment by jessepinho** [comment]
@tsmacdonald This is just missing the centering of the photos on the Photos page. I'm at 2:15 right now—we can merge and ship this just to get these changes out the door and I can do the photos later—just not sure exatly when I'll get to it (not sure what I want to do w/ the photos yet).

**Comment by tsmacdonald** [comment]
:sheep: it, looks like :panda_face: :cake: to me.

**Pull request merged**
